### PR TITLE
Buoyancy

### PR DESCRIPTION
**Pull request by AmpCat**
Updated buoyancy values so all the pods float.
Also fixed a few localization tags and added some search tags (REKT and OTAV where appropriate)
Also spelled buoyancy correctly in github.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
I can't accept this as it is, yet.  You have a lot of files ending in .cfgbak, while I assume that those are backup files, I'd rather let you clean it up.
To do so, once you've done the cleanup on your local repo, just commit it and push it into the same branch, the PR will automatically be updated.

**Comment by AmpCat** [comment]
I thought I deleted all those. I'll take a look and see what happened.

**Comment by linuxgurugamer** [comment]
No problem, just ping me when it's been udpated

**Comment by AmpCat** [comment]
Okay, this is strange. My local repository doesn't contain any of those
cfgbak files. How're they getting up there? And more importantly, how do I
tell git to remove files I don't have on my local repository?

**Comment by AmpCat** [comment]
Hm, okay, I think I see an issue. I have an old (misspelled) branch which does have those files, but my current one does not. I'll redo the pull request with the current version. (I hope)

**Comment by AmpCat** [comment]
Did you see the new pull request? I think I got everything sorted out.

**Comment by linuxgurugamer** [comment]
Yes, been busy, hope to get to this later this evening

**Pull request closed without merging**
